//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TwoLettersCode { get; set; }
        public string ThreeLettersCode { get; set; }
        public Nullable<int> NumberCode { get; set; }
        public int Order { get; set; }
    }
}
