//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentHistory
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public bool ReceivedDocument { get; set; }
        public string UserId { get; set; }
        public System.DateTime AttempOn { get; set; }
    }
}
