//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string OS { get; set; }
        public string DeviceType { get; set; }
        public string DeviceSerial { get; set; }
        public string BrowserType { get; set; }
        public string UserHostAddress { get; set; }
        public string UserLocation { get; set; }
        public bool NormalAccess { get; set; }
        public bool EmailSent { get; set; }
        public System.DateTime AttempOn { get; set; }
    }
}
