//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCenter
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string DeviceId { get; set; }
        public string Content { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> RelateRecordId { get; set; }
        public Nullable<int> SubRelateRecordId { get; set; }
        public string RecordNumber { get; set; }
        public int Type { get; set; }
        public string ReceivedUserId { get; set; }
        public bool HaveSeen { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
